### PR TITLE
ci: add luarocks-tag-release workflow

### LINKED ISSUE #11: fzy-lua fails to install on Windows
Hey :wave: 

Attepting `luarocks install fzy` on Windows fails with

```
src/match.c(18): fatal error C1083: Cannot open include file: 'strings.h': No such file or directory
```

https://github.com/nvim-neorocks/rocks-binaries/actions/runs/8191805472/job/22401866175#step:9:815

There are two ways I could think of to fix this:

1. Use a [platform override](https://github.com/luarocks/luarocks/wiki/platform-overrides) in the rockspec to prevent it from trying to compile the native library.
2. Add an adapter header ([see this PR](https://github.com/google/gumbo-parser/pull/429/files)). I'm not sure if there are any other headers that might be missing on Windows though.

### PR DESCRIPTION
**Pull request by mrcjkb**
Closes #11

### CODE REVIEW

**Comment by mrcjkb** [comment]
@swarn One thing I forgot to mention: The way I've implemented this workflow, it only triggers if you push a tag, but not if you create a tag via GitHub Releases.

There's a more complicated setup that solves this problem, which we provide [a tutorial for](https://github.com/nvim-neorocks/sample-luarocks-plugin).

But I think for your case, this simple approach should suffice :smile:.

**Comment by swarn** [comment]
I agree!

Running into a little bug here, I think. I added the release tag, the ran the workflow manually. It uploaded a `fzy-lua` rock, rather than a `fzy` rock.

**Comment by swarn** [comment]
Ha, I added a `name` field, but now it uploads a `main-1` rock to [luarocks](https://luarocks.org/modules/sethwarn/fzy) rather than a `1.0.1-1` rock. I'll stop messing with it until you get a change to check it out.

**Comment by mrcjkb** [comment]
Oh yeah, I missed that :sweat_smile: 
I see you've already added the name.

**Comment by mrcjkb** [comment]
> Ha, I added a `name` field, but now it uploads a `main-1` rock to [luarocks](https://luarocks.org/modules/sethwarn/fzy) rather than a `1.0.1-1` rock. I'll stop messing with it until you get a change to check it out.

This is probably because you triggered it on the `main` branch.
If you trigger it on the tag, it should work (but it might use the old workflow file, so it might be best to delete the tag and create a new one).

**Comment by swarn** [comment]
fzy 1.0.2 is live on luarocks and your windows builds should all succeed now. Thanks for the help!

**Comment by mrcjkb** [comment]
Yay :rocket: 

It's still failing on the windows GitHub runner I'm using, with

```
fzy_native.obj : error LNK2019: unresolved external symbol has_match referenced in function filter
fzy_native.obj : error LNK2019: unresolved external symbol match referenced in function score
fzy_native.obj : error LNK2019: unresolved external symbol match_positions referenced in function filter
C:\Users\RUNNER~1\AppData\Local\Temp\luarocks_build-fzy-1.0.2-1-4475950\fzy_native.dll : fatal error LNK1120: 3 unresolved externals
```

:thinking: I wonder if that's a 32 bit vs 64 bit issue, since I'm using `windows-2019`,
or maybe it's missing some build dependencies.

**Comment by mrcjkb** [comment]
Oh, I know what it is.
The luarocks-tag-release action needs a rockspec template in your case.
I will add this in another PR

**Pull request merged**
