### PR TITLE
tests: compatibility with `luarocks test`

### PR DESCRIPTION
**Pull request by mrcjkb**

### CODE REVIEW

**Review by teto — APPROVED** [review]

**Comment by swarn** [comment]
Looks good, thanks for the pr!

**Comment by swarn** [comment]
I spoke too soon, the Windows test is failing.

**Comment by mrcjkb** [comment]
Yup, just saw that.
Will look into it now...

**Comment by mrcjkb** [comment]
:thinking: `busted` released [version 2.2.0](https://github.com/lunarmodules/busted/releases) last month, removing the unused `luafilesystem` dependency. 

I think the failed Windows build is caused by `busted` not being pinned - it appears `luafilesystem` is either required on Windows, or it hasn't been removed completely (i.e. they forgot the Windows code base).

**Pull request merged**
